id: mini_1_pressed
alias: 'Minimote Button 1 Pressed'
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.minimote
      scene_id: 1
action:
  service: homeassistant.turn_on
  entity_id: group.living_room