id: mini_1_held
alias: 'Minimote Button 1 Held'
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.minimote
      scene_id: 2
action:
  service: homeassistant.turn_off
  entity_id: group.living_room