id: mini_2_pressed
alias: 'Minimote Button 2 Pressed'
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.minimote
      scene_id: 3
action:
  service: homeassistant.turn_on
  entity_id: switch.hallway_lights_switch