id: mini_2_held
alias: 'Minimote Button 2 Held'
trigger:
  - platform: event
    event_type: zwave.scene_activated
    event_data:
      entity_id: zwave.minimote
      scene_id: 4
action:
  service: homeassistant.turn_off
  entity_id: switch.hallway_lights_switch